### ISSUE TITLE
Fade on MouseEnter/Leave

### ISSUE THREAD

**Issue by plugdj** [vitch/jScrollPane#276]
I made a few modifications to make the scrollbar fade in and out on mouse enter and leave. Not sure it's worth a pull request but here for anyone else who wants this functionality.

``` css
.jspVerticalBar {
  opacity: 0;
  transition: all 0.3s ease;
}
.jspVerticalBar.hover {
  opacity: 1;
  transition: all 0.2s ease;
}
```

``` javascript
// LINE 73
verticalDragPosition, horizontalDrag, dragMaxX, horizontalDragPosition, isOver,
// LINE 121
container = $('<div class="jspContainer" />')
    .on('mouseenter', function(){
    isOver = true;
    if (event.which !== 1) container.find('.jspVerticalBar').addClass('hover');
    else $(document).on('mouseup', checkOver);
})
    .on('mouseleave', function(event){
    isOver = false;
    if (event.which !== 1) container.find('.jspVerticalBar').removeClass('hover');
    else $(document).on('mouseup', checkOver);
})
    .css({
        'width': paneWidth + 'px',
        'height': paneHeight + 'px'
}
/// LINE 262 (after initialize)
function checkOver()
{
    if (!isOver) container.find('.jspVerticalBar').removeClass('hover');
    else container.find('.jspVerticalBar').addClass('hover');
    $(document).off('mouseup', checkOver);
}
```
